name: leekbox
description: A project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+91

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  percent_indicator: ^4.2.3
  dotted_border: ^2.0.0+1
  timeago: ^3.3.0
  nil: ^1.1.1
  tuple: ^2.0.1
  #protobuf: ^2.1.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  google_fonts: ^4.0.3
  animated_text_kit: ^4.2.2
  #
  built_collection: ^5.1.1
  built_value: ^8.4.4
  json_annotation: ^4.8.0
  #
  freezed_annotation: ^2.2.0
  #
  window_manager: ^0.3.2
  #
  screenshot: ^1.3.0
  #
  flutter_zoom_drawer: ^3.0.4+1
  #  动态主题
  dynamic_color: ^1.6.2
  # 文件读写
  path_provider: ^2.0.14
  # 状态管理 + 路由
  flutter_riverpod: ^2.3.5
  hooks_riverpod: ^2.3.5
  riverpod_annotation: ^2.1.0
  go_router: ^6.5.7
  #
  package_info_plus: ^3.1.0
  device_info_plus: ^8.2.0
  battery_plus: ^3.0.4
  #  网络检查
  connectivity_plus: ^3.0.4
  internet_connection_checker: ^1.0.0+1
  #  network_info_plus: ^3.0.2
  # 适配
  flutter_screenutil: ^5.7.0
  # 动画
  animations: ^2.0.7
  #  supercharged: ^2.1.1
  #  simple_animations: ^5.0.0+3
  # 闪屏
  flutter_native_splash: ^2.2.19
  # 下拉 刷新
  pull_to_refresh: ^2.0.0
  # 取色
  #  palette_generator: ^0.3.3+2
  # 权限
  permission_handler: ^10.1.0
  # card 角标
  rotated_corner_decoration: ^2.1.0
  # 角标
  badges: ^3.1.1
  # 时间线 https://github.com/JHBitencourt/timeline_tile
  timeline_tile: ^2.0.0
  # 输入框
  #  pinput: ^2.2.12
  # 瀑布流
  waterfall_flow: ^3.0.2
  shimmer: ^2.0.0
  # 媒体选择
  #  photo_manager: ^2.6.0
  #  wechat_assets_picker: ^8.2.0
  #  wechat_camera_picker: ^3.6.5
  # 视频播放
  chewie: ^1.4.0
  video_player: ^2.6.0
  # 打开链接
  url_launcher: ^6.1.10
  # 版本升级
  r_upgrade: ^0.4.2
  version: ^3.0.2
  # 倒计时
  timer_count_down: ^2.2.2
  # 滚动快速回到顶部
  #  scrolls_to_top: ^2.1.0
  # 头像发光～～～
  avatar_glow: ^2.0.2
  # 加密
  #  crypto: ^3.0.2
  # 二维码：扫码
#  flutter_scankit: ^1.2.4
  # 动画
  lottie: ^2.3.2
  rive: ^0.10.4
  #  网络请求
  dio: ^5.0.3
  dio_cookie_manager: ^2.1.3
  dio_http2_adapter: ^2.1.0
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^3.0.1
  #
  app_settings: ^4.2.0
  # 弹窗
  flutter_smart_dialog: ^4.9.0+4
  # WeChatSDK 插件
  fluwx: ^3.13.1
  # 视频图片压缩
  #  video_compress: ^3.1.0
  #  flutter_image_compress: ^1.1.3
  # 存储 ？？？
  shared_preferences: ^2.0.20
  # 数据存储 基于sqlite3 封装
  drift: ^2.7.0
  db_viewer: ^1.0.3
  # isar 缓存
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  # 富文本编辑器：markdown
  flutter_quill: ^7.1.9
  # 图表库
  #  fl_chart: ^0.66.0
  syncfusion_flutter_datagrid: ^21.1.38
  # 图片缓存
  cached_network_image: ^3.2.3
  #
  flutter_svg: ^2.0.5
  # 图片预览
  photo_view: ^0.14.0
  # 模糊图片
  #  blurhash_dart: ^1.2.1
  # 图片库： https://github.com/alibaba/power_image
  #  power_image: ^0.1.0-pre.2
  image_picker: ^0.8.7
  #  image: ^3.2.2
  # 新拟物
  # flutter_neumorphic: ^3.2.0
  #
  webview_flutter: ^4.2.0
  # 本地通知
  flutter_local_notifications: ^13.0.0
  # flutter_local_notifications 依赖
  flutter_timezone: ^1.0.4
  intl: any
  #
  #  table_calendar: ^3.0.7
  #
  wakelock: ^0.6.2
  #
  local_auth: ^2.1.2
  # 高刷
  flutter_displaymode: ^0.6.0
  #  tensorflow
  #  tflite_flutter: ^0.9.0
  #  tflite_flutter_helper: ^0.3.1
  # bottom_bar
  salomon_bottom_bar:
    path: packages/salomon_bottom_bar
  sliding_clipped_nav_bar:
    path: packages/sliding_clipped_nav_bar
  txt_nav_bar:
    path: packages/txt_nav_bar
  bottom_blur_bar:
    path: packages/bottom_blur_bar
  # tabbar滑动方式：类似酷狗
  custom_tabbar:
    path: packages/custom_tabbar
  #  项目分包处理
  leekbox_infra:
    path: packages/leekbox_infra
  #                               Dev Tools  + Test
  # 不同分辨率的手机上查看UI效果
  device_preview: ^1.1.0
  #
  mockito: ^5.3.2

# 强制升级版本
#dependency_overrides:
#  power_image_ext: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # git hook 相关
  process_run: ^0.13.0
  git_hooks: ^1.0.0
  #
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  built_value_generator: ^8.4.4
  #
  flutter_gen_runner: ^5.2.0
  # 数据模型generator
  freezed: ^2.3.2
  # 路由generator
  go_router_builder: ^1.1.7
  # 状态管理generator
  riverpod_generator: ^2.2.0
  # 国际化generator
  intl_utils: any
  # generator
  isar_generator: ^3.0.5
  #
  drift_dev: ^2.6.0
  # logo 生成插件   flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  # 打包 windows
  msix: ^3.11.0



# flutter packages pub run build_runner build
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  #
  integrations:
    flutter_svg: true
    rive: false
    lottie: true

  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter
    exclude:
      - assets/tflites/
      - assets/rives/
      - assets/lotties/

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/videos/
    - assets/images/
    - assets/images/common/
    - assets/images/splash/
    - assets/images/mine/
    - assets/images/login/
    - assets/images/design_course/
    - assets/images/intro/
    - assets/fonts/
    - assets/local/
    - assets/tflites/
    - assets/rives/
    - assets/lotties/

# 动态加载
#  fonts:
#    # 电子屏：时间显示 ：紧凑
#    - family: Digital7
#      fonts:
#        - asset: assets/fonts/digital-7.ttf
#          style: italic
#    # 数字： 涉及金额需要使用的字体
#    - family: DINPro
#      fonts:
#        - asset: assets/fonts/DIN-Pro-Regular.otf
#          style: normal
#
flutter_intl:
  enabled: true

# window 打包 config
msix_config:
  display_name: Leekbox
  msix_version: 1.0.0.0
