name: leekbox
description: A project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.6.25+101

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  #
  percent_indicator: ^4.2.3
  #
  dotted_border: ^2.1.0
  # display something like "now", "an hour ago", "~1y"
  timeago: ^3.6.1
  nil: ^1.1.1
  #
  tuple: ^2.0.2
  protobuf: ^3.1.0
  uuid: ^4.3.3
  equatable: ^2.0.5
  # google_fonts: ^5.0.0
  animated_text_kit: ^4.2.2
  #
  built_collection: ^5.1.1
  built_value: ^8.9.1
  json_annotation: ^4.8.1
  #
  freezed_annotation: ^2.4.1
  # 文件读写
  path_provider: ^2.1.2
  # 状态管理 + 路由
  flutter_riverpod: ^2.4.10
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  go_router: ^13.2.0
  #
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  #  battery_plus: ^4.0.1
  #  网络检查
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  network_info_plus: ^4.1.0+1
  # 适配
  flutter_screenutil: ^5.9.0
  # 动画
  animations: ^2.0.11
  # 闪屏
  flutter_native_splash: ^2.3.10
  # 下拉 刷新
  pull_to_refresh: ^2.0.0
  # 权限
  permission_handler: ^11.3.0
  # card 角标
  rotated_corner_decoration: ^2.1.0
  # 角标
  badges: ^3.1.2
  # 时间线 https://github.com/JHBitencourt/timeline_tile
  timeline_tile: ^2.0.0
  # 输入框
  #  pinput: ^2.2.12
  # 瀑布流
  #  waterfall_flow: ^3.0.2
  #  shimmer: ^3.0.0
  # 媒体选择
  #  photo_manager: ^2.6.0
  #  wechat_assets_picker: ^8.5.0
  #  wechat_camera_picker: ^3.6.5
  # 视频播放
  #  chewie: ^1.4.0
  video_player: ^2.8.2
  # 音频播放器
  audioplayers: ^5.2.1
  # 打开链接
  url_launcher: ^6.2.5
  # 版本升级
  r_upgrade: ^0.4.2
  version: ^3.0.2
  # 倒计时
  timer_count_down: ^2.2.2
  # 滚动快速回到顶部
  #  scrolls_to_top: ^2.1.0
  # 头像发光～～～
  avatar_glow: ^3.0.1
  # 加密
  #  crypto: ^3.0.2
  # 二维码：扫码
  #  flutter_scankit: ^1.2.4
  # 动画
  lottie: ^3.1.0
  #  rive: ^0.11.4
  #  网络请求
  dio: ^5.3.2
  dio_http2_adapter: ^2.4.0
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  #
  app_settings: ^5.1.1
  # 弹窗
  flutter_smart_dialog: ^4.9.6
  # WeChatSDK 插件
  #  fluwx: ^4.2.5
  # 视频图片压缩
  #  video_compress: ^3.1.0
  #  flutter_image_compress: ^1.1.3
  # 存储 ？？？
  shared_preferences: ^2.2.2
  # 数据存储 基于sqlite3 封装 : 历史数据
#  drift: ^2.11.0
#  db_viewer: ^1.0.3
  # isar 缓存
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # 富文本编辑器：markdown
  #  flutter_quill: ^7.1.14
  # 图表库
  #  fl_chart: ^0.66.0
  #  syncfusion_flutter_datagrid: ^22.1.37
  # 图片缓存
  cached_network_image: ^3.3.1
  #
  flutter_svg: ^2.0.10+1
  # 图片预览
  photo_view: ^0.14.0
  # 模糊图片
  #  blurhash_dart: ^1.2.1
  #  image_picker: ^0.8.7
  #  image: ^3.2.2
  # 新拟物
  # flutter_neumorphic: ^3.2.0
  #
  webview_flutter: ^4.7.0
  # 本地通知
  flutter_local_notifications: ^16.3.2
  flutter_timezone: ^1.0.8
  #
  intl: ^0.18.1
  #
  #  wakelock: ^0.6.2
  #
  #  local_auth: ^2.1.2
  # 高刷 ｜ only android
  #  flutter_displaymode: ^0.6.0
  #  tensorflow
  #  tflite_flutter: ^0.9.0
  #  tflite_flutter_helper: ^0.3.1
  # bottom_bar
  salomon_bottom_bar:
    path: packages/salomon_bottom_bar
  sliding_clipped_nav_bar:
    path: packages/sliding_clipped_nav_bar
  # tabbar滑动方式：类似酷狗
  custom_tabbar:
    path: packages/custom_tabbar
  #  项目分包处理
  leekbox_infra:
    path: packages/leekbox_infra
  #                               Dev Tools  + Test
  # 不同分辨率的手机上查看UI效果
  device_preview: ^1.1.0
  #
  #  mockito: ^5.4.2
  # PC 窗口管理
#  window_manager: ^0.3.5

# 强制升级版本
#dependency_overrides:
#  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  process_run: ^0.14.2
  # git hook
  git_hooks: ^1.0.1
  #
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  built_value_generator: ^8.6.1
  #
  flutter_gen_runner: ^5.4.0
  # 数据模型generator
  freezed: ^2.4.7
  # 路由generator
  go_router_builder: ^2.4.1
  # 状态管理generator
  riverpod_generator: ^2.3.11
  # 国际化generator
  intl_utils: ^2.8.5
  # generator
  isar_generator: ^3.1.0+1
  #
#  drift_dev: ^2.11.0
  # logo 生成插件   flutter pub run flutter_launcher_icons
#  flutter_launcher_icons: ^0.13.1
  # 打包 windows
#  msix: ^3.15.1

# flutter packages pub run build_runner build
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  #
  integrations:
    flutter_svg: true
    rive: false
    lottie: true

  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter
    exclude:
      - assets/tflites/
      - assets/rives/
      - assets/lotties/

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/videos/
    - assets/images/
    - assets/images/common/
    - assets/images/splash/
    - assets/images/mine/
    - assets/images/login/
    - assets/images/design_course/
    - assets/images/intro/
    - assets/fonts/
    - assets/local/
    - assets/tflites/
    - assets/rives/
    - assets/lotties/

# 动态加载
#  fonts:
#    # 电子屏：时间显示 ：紧凑
#    - family: Digital7
#      fonts:
#        - asset: assets/fonts/digital-7.ttf
#          style: italic
#    # 数字： 涉及金额需要使用的字体
#    - family: DINPro
#      fonts:
#        - asset: assets/fonts/DIN-Pro-Regular.otf
#          style: normal
#
flutter_intl:
  enabled: true

# window 打包 config
msix_config:
  display_name: Leekbox
  msix_version: 1.0.0.0
