name: leekbox
description: A project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+91

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  phosphor_flutter: ^1.4.0
  mockito: ^5.3.2
  animations: ^2.0.7
  nil: ^1.1.1
  tuple: ^2.0.1
  ffi: ^2.0.1
  isolates: ^3.0.3+8
  #  protobuf: ^2.1.0
  #  uuid: ^3.0.7
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  built_value: ^8.4.4
  freezed_annotation: ^2.2.0
  #
  #  flutter_secure_storage: ^7.0.1
  #  sign_in_with_apple: ^4.2.0
  #  local_auth: ^2.1.2
  # 存储
  shared_preferences: ^2.0.18
  #
  flutter_native_splash: ^2.2.19
  #  动态主题
  dynamic_color: ^1.6.2
  # 文件读写
  path_provider: ^2.0.13
  # 官方推荐：状态管理 + 路由   VS  getx
  flutter_riverpod: ^2.3.2
  hooks_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  go_router: ^6.2.0
  #  字体
  #  google_fonts: ^4.0.3
  #
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  #  网络检查
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  #  network_info_plus: ^3.0.2
  # 适配屏幕
  flutter_screenutil: ^5.7.0
  #  下拉 刷新
  pull_to_refresh: ^2.0.0
  #  取色
  palette_generator: ^0.3.3+2
  # 权限
  permission_handler: ^10.1.0
  # card 角标 https://github.com/kalaganov/corner_decoration
  rotated_corner_decoration: ^2.1.0
  # 角标 https://github.com/yako-dev/flutter_badges
  badges: ^3.0.2
  # 时间线 https://github.com/JHBitencourt/timeline_tile
  #  timeline_tile: ^2.0.0
  # 输入框
  #  pinput: ^2.2.12
  # 瀑布流
  waterfall_flow: ^3.0.2
  # bottom_bar
  salomon_bottom_bar: ^3.3.1
  sliding_clipped_nav_bar: ^3.1.0+3
  #
  #  scrollable_positioned_list: ^0.3.5
  # 引导插件
  # showcaseview: ^2.0.0+1
  #  加载指示器
  #  loading_indicator: ^3.1.0
  # 媒体选择
  #  wechat_assets_picker: ^8.2.0
  #  wechat_camera_picker: ^3.6.5
  # 视频播放
  #  chewie: ^1.3.6
  #  video_player: ^2.4.9
  # 打开链接
  url_launcher: ^6.1.10
  #
  #  animated_text_kit: ^4.2.2
  # 版本升级
  r_upgrade: ^0.4.2
  version: ^3.0.2
  # 倒计时
  timer_count_down: ^2.2.2
  #
  avatar_glow: ^2.0.2
  # 定位
  #  geolocator: ^9.0.2
  # 加密
  #  crypto: ^3.0.2
  #  滑块
  #  carousel_slider: ^4.2.1
  #
  syncfusion_flutter_datagrid: ^20.3.60
  #
  #  flutter_rating_bar: ^4.0.1
  #
  #  flutter_scankit: ^1.2.4
  # 动画
  lottie: ^2.2.0
  rive: ^0.10.3
  #  网络请求
  dio: ^5.0.2
  dio_cookie_manager: ^2.1.2
  dio_http2_adapter: ^2.1.0
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^3.0.1
  #
  app_settings: ^4.2.0
  #
  oktoast: ^3.3.1
  # WeChatSDK 插件
  #  fluwx: ^3.9.2
  #  链接
  #  uni_links: ^0.5.1
  # 视频图片压缩
  #  video_compress: ^3.1.0
  #  flutter_image_compress: ^1.1.3
  # 数据存储 基于sqlite3 封装
  drift: ^2.5.0
  # 查看本地存储的sqlite数据
  #  db_viewer: ^1.0.3
  # 富文本编辑器
  #  flutter_quill: ^6.0.10
  # 图表库
  #  fl_chart: ^0.66.0
  #  skeletons: ^0.0.3
  #
  flutter_svg: ^2.0.3
  # 图片缓存
  cached_network_image: ^3.2.3
  # 图片预览
  photo_view: ^0.14.0
  # 模糊图片
  blurhash_dart: ^1.2.1
  # 图片库： https://github.com/alibaba/power_image
  #  power_image: ^0.1.0-pre.2
  #  image_picker: ^0.8.6
  #  image: ^3.2.2
  #
  # flutter_neumorphic: ^3.2.0
  #  多滚动集合
  #  linked_scroll_controller: ^0.2.0
  # 不同分辨率的手机上查看UI效果
  device_preview: ^1.1.0
  #
  webview_flutter: ^4.0.6

  # 本地通知
  #  flutter_local_notifications: ^12.0.2
  #
  #  table_calendar: ^3.0.7
  #  tensorflow:
  #  tflite_flutter: ^0.9.0
  #  tflite_flutter_helper: ^0.3.1
  # need upgrade, clone local edit
  wakelock: ^0.6.2
  #  in_app_review: 2.0.4

  #  flutter_smart_dialog: ^4.7.1

  #  tflite_flutter:
  #    path: packages/tflite_flutter_plugin
  #  tflite_flutter_helper:
  #    path: packages/tflite_flutter_helper
  #  更该项目名：pub global run rename --bundleId com.myDomain.myApp or pub global run rename --appname "MyApp"
  #  rename: ^2.1.1
  #
  swipe_to: ^1.0.2
  #
  hidable: ^1.0.3
  #
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  #  项目分包处理
  leekbox_infra:
    path: packages/leekbox_infra
  # 类似酷狗tabbar滑动方式
  custom_tabbar:
    path: packages/custom_tabbar


# 强制升级版本
#dependency_overrides:
#  power_image_ext: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # git hook 相关
  process_run: ^0.12.5+2
  git_hooks: ^1.0.0
  #
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  #
  flutter_gen_runner: ^5.2.0
  # 数据模型generator
  freezed: ^2.3.2
  # 路由generator
  go_router_builder: ^1.1.6
  # 状态管理generator
  riverpod_generator: ^2.1.4
  # 国际化generator
  intl_utils: ^2.8.2
  # 缓存generator
  isar_generator: ^3.0.5
  #
  drift_dev: ^2.5.1
  # logo 生成插件   flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.12.0

# flutter packages pub run build_runner build
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  #
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      # Assets.imagesChip
      # style: camel-case

      # Assets.images_chip
      # style: snake-case

      # Assets.images.chip (default style)
      style: dot-delimiter
    exclude:
      - assets/flare/

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

  colors:
    enabled: true
    outputs:
      class_name: MyColor
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/splash/
    - assets/images/mine/
    - assets/images/design_course/
    - assets/images/intro/
    - assets/fonts/
    - assets/local/
    - assets/tflites/
    - assets/rives/
    - assets/lotties/

  fonts:
    # 电子屏：时间显示 ：紧凑
    - family: Digital
      fonts:
        - asset: assets/fonts/digital-7.ttf
          style: italic
    # 数字： 涉及金额需要使用的字体
    - family: DINPro
      fonts:
        - asset: assets/fonts/DIN-Pro-Regular.otf
          style: normal
#
flutter_intl:
  enabled: true
