name: sliding_clipped_nav_bar
description: Bottom Navigation Bar with sliding menu icon and text with clipping effect, it also has ripple effect when tapped.

version: 3.1.0+4
repository: https://github.com/watery-desert/sliding_clipped_nav_bar

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0  

flutter: 
  uses-material-design: true
